services:
  Backend:
    image: "ghcr.io/felizcoder/crewstand.backend:latest"
    restart: always
    container_name: "crewstand-backend"
    environment:
      - "FLOWMETER_COUNT=1"
      - "GPIO_MODE=CAN"
      - "FLOWMETER_COUNT=1"
      - "GPIO_MODE=CAN"
      - "INFLUXDB_BUCKET=${INFLUXDB_BUCKET}"
      - "INFLUXDB_ORG=${INFLUXDB_ORG}"
      - "INFLUXDB_TOKEN=${INFLUXDB_TOKEN}"
      - "INFLUXDB_URL=http://localhost:8086"
      - "PROPORTIONAL_GPIO=11"
      - "PROPORTIONAL_MODE=CAN"
      - "PUMP_GPIO=17"
      - "SOLENOID_GPIO=26,19,6,5,22,27"
      - "MISSION_WAIT_SECONDS=10"
    network_mode: "host"
    privileged: true

  Frontend:
    image: "ghcr.io/felizcoder/crewstand.frontend:latest"
    restart: always
    depends_on:
      - "Backend"
    container_name: "crewstand-frontend"
    environment:
      - "BACKEND_URI=http://${BACKEND_BASE}"
      - "BACKEND_URI=http://${BACKEND_BASE}"
    ports:
      - "80:3000"

  Grafana:
    image: "ghcr.io/felizcoder/crewstand.grafana:latest"
    container_name: "crewstand-grafana"
    depends_on:
      - "InfluxDB"
    restart: always
    environment:
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "INFLUX_TOKEN=${INFLUXDB_TOKEN}"
      - "INFLUX_URL=http://influxdb:8086"
      - "NO_PROXY=influxdb"
      - "no_proxy=influxdb"
    ports:
      - "3000:3000"

  InfluxDB:
    image: "influxdb:2.7.11"
    restart: always
    container_name: "crewstand-influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "${INFLUX_CONFIG_VOLUME}:/etc/influxdb2"
      - "${INFLUX_DATA_VOLUME}:/var/lib/influxdb2"

  Pid-Control:
    image: "ghcr.io/felizcoder/crewstand.pid_control:latest"
    container_name: "crewstand-pidcontrol"
    depends_on:
      - "Backend"
    restart: always
    environment:
      - "BACKEND_BASE=${BACKEND_BASE}"
      - "BACKEND_BASE=${BACKEND_BASE}"
      - "INFLUXDB_BUCKET=${INFLUXDB_BUCKET}"
      - "INFLUXDB_ORG=${INFLUXDB_ORG}"
      - "INFLUXDB_TOKEN=${INFLUXDB_TOKEN}"
      - "INFLUXDB_URL=http://influxdb:8086"
      - "PID_KD=0.2"
      - "PID_KI=1"
      - "PID_KP=2.75"
      - "PID_KD=0.2"
      - "PID_KI=1"
      - "PID_KP=2.75"
      - "PID_OUTPUT_MAX=100"
      - "PID_OUTPUT_MIN=0"
      - "PROJECT_NAME=swncrew pid controller"
      - "PROPORTIONAL_VALVE_ID=0"
      - "SENSOR_ID=0"
  Sensor-Gateway:
    image: "ghcr.io/felizcoder/crewstand.sensor_gateway:latest"
    container_name: "crewstand-sensorgateway"
    restart: always
    depends_on:
      - "Backend"
    environment:
      - "backend_sensor_url=http://${BACKEND_BASE}"
      - "measurement_range=[[0,25]]"
      - "read_interval_s=0.5"
      - "sensor_count=1"
      - "serial_port=/dev/ttyAMA0"
      - "serial_baud_rate=250000"
      - "voltage_range=[0.6,3]"
    volumes:
      - "/dev/ttyAMA0:/dev/ttyAMA0:rw"
    privileged: true

  Classifier:
    image: "ghcr.io/felizcoder/crewstand.lgbmclassifier:10-post-classified-missions-to-backend"
    container_name: "crewstand-LGBMclassifier"
    restart: always
    depends_on:
      - "Backend"
    environment:
      - "BACKEND_BASE=${BACKEND_BASE}"
      - "INFLUXDB_BUCKET=${INFLUXDB_BUCKET}"
      - "INFLUXDB_ORG=${INFLUXDB_ORG}"
      - "INFLUXDB_TOKEN=${INFLUXDB_TOKEN}"
      - "INFLUXDB_URL=http://influxdb:8086"

    